package ru.itis.consts;

import java.util.Random;

public final class MapSchemas {
    public static final String BAD_MAP =   "           o           " +
                                           " b b b b b   b b b b b " +
                                           " b b b b b   b b b b b " +
                                           " b b b b b   b b b b b " +
                                           "bbbbbbbbbbb bbbbbbbbbbb" +
                                           "bbbbbbbbbbb bbbbbbcbbcb" +
                                           "bbbbbbbbbbb bbbbbbbccbb" +
                                           "cbbbbbcbcbb bbcbcbbbbbc" +
                                           "bcbbbcbbbcb bcbbcbbbbcc" +
                                           "bbcbcbbbbbc cbbbcbbbcbc" +
                                           "bbbcbbbbbbb bbbbcbbcbbc" +
                                           "bbcbcbbbbbc bbbbcbcbbbc" +
                                           "bcbbbcbbbcb bbbbccbbbbc" +
                                           "cbbbbbcbcbb bbbbcbbbbbc" +
                                           "           m           ";

    public static final String FIRST_MAP =    "           o           " +
                                              "  bb  bb bb bb bb  bb  " +
                                              "  bb  bb bb bb bb  bb  " +
                                              "  bb  bb bbcbb bb  bb  " +
                                              "  bb  bb bb bb bb  bb  " +
                                              "  bb  bb       bb  bb  " +
                                              "         bb bb         " +
                                              "c   bbbb       bbbb   c" +
                                              "         bb bb         " +
                                              "  bb  bb bb bb bb  bb  " +
                                              "  bb  bb bbbbb bb  bb  " +
                                              "  bb  bb bb bb bb  bb  " +
                                              "  bb  bb bb bb bb  bb  " +
                                              "  bb  bb bb bb bb  bb  " +
                                              "           m           ";

    public static final String SECOND_MAP =   "           o           " +
                                              "ggbbb b b cc bb  bb bb " +
                                              "ggggggg bb  bb   bb bb " +
                                              "ggwwwwwwwwwwwwwwww  www" +
                                              "  bb                   " +
                                              "    bbbbbbbbbbbbbbccccc" +
                                              "bbbb    bb bbbgbccbbbbb" +
                                              "c   bbbbggggggggggg   c" +
                                              "www  wwwwwwwww  wwwwwww" +
                                              "www  wwwwwwwww  wwwwwww" +
                                              "ggggggggggggggggggggggg" +
                                              "ggggggggggggggggggggggg" +
                                              "   bb  bb  bb bb bb bb " +
                                              "  bb  bb c  c c b bb   " +
                                              "           m           ";

    // 23 на 15
    public static String autoGeneratedMap() {
        String[] elements = new String[]{" ", "w", "b", " ", "c", "g", "b", " "};
        Random random = new Random();
        StringBuilder stringBuilder = new StringBuilder();
        for(int i = 0; i < 345; i++) {
            if(i < 23 || i > 321) stringBuilder.append(" ");
            else stringBuilder.append(elements[random.nextInt(elements.length)]);
        }
        return stringBuilder.toString();
    }
}